[package]
name = "bpaf_cauwugo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
categories = ["command-line-interface", "command-line-utilities"]
repository.workspace = true
keywords = ["cargo", "cargo-frontend", "cli", "completion", "dynamic-completion"]
readme = "README.md"
description = "A cargo frontend with dynamic completion"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpaf = { workspace = true, features = ["derive", "autocomplete"] }
cargo_metadata.workspace = true
once_cell.workspace = true

[[bin]]
name = "cauwugo"
path = "src/main.rs"
